/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjava;

import javax.swing.JFrame;
import java.util.Random;

/**
 *
 * @author thesa
 */
public class NewJFrame extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {      //create frame
        initComponents();
    }
    private int n1,n2,n3,n4,score;          //n1-4 is rundom number 
    private boolean b1=true,b2=false,b3=true,b4=true,readyop=false;
    private String STRans="",op="";
    private static String removeLastChar(String str) {    
        return str.substring(0, str.length() - 1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        BACKGROUND = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        how2play = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scorelabel = new javax.swing.JLabel();
        scoreText = new javax.swing.JLabel();
        number1 = new javax.swing.JLabel();
        number2 = new javax.swing.JLabel();
        number3 = new javax.swing.JLabel();
        number4 = new javax.swing.JLabel();
        ans = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        root = new javax.swing.JButton();
        fact = new javax.swing.JButton();
        power = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        restart = new javax.swing.JButton();
        home = new javax.swing.JButton();
        next = new javax.swing.JButton();
        N1 = new javax.swing.JButton();
        N2 = new javax.swing.JButton();
        N3 = new javax.swing.JButton();
        N4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        play1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BACKGROUND.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wine SK\\Desktop\\java\\photo\\ปก.gif")); // NOI18N
        jPanel1.add(BACKGROUND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 520));

        play.setText("jButton1");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        jPanel1.add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 150, 80));

        how2play.setText("jButton1");
        how2play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                how2playActionPerformed(evt);
            }
        });
        jPanel1.add(how2play, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 220, 60));

        exit.setText("jButton2");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 120, 60));

        jLayeredPane2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(670, 520));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.setVisible(false);

        scorelabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        scorelabel.setText("score : ");
        jPanel2.add(scorelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 120, 20));

        scoreText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        scoreText.setText("0");
        jPanel2.add(scoreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 20, 40));

        number1.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        number1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\0.png")); // NOI18N
        jPanel2.add(number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        number2.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        number2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\0.png")); // NOI18N
        jPanel2.add(number2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        number3.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        number3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\0.png")); // NOI18N
        jPanel2.add(number3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        number4.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        number4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\0.png")); // NOI18N
        jPanel2.add(number4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        ans.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jPanel2.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 170, 80));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wine SK\\Desktop\\java\\photo\\game.gif")); // NOI18N
        jPanel2.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 520));

        plus.setText("plus");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        jPanel2.add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, 60));

        minus.setText("minus");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        jPanel2.add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 60, 60));

        multi.setText("multi");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        jPanel2.add(multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 60, 60));

        divide.setText("divide");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        jPanel2.add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 60, 60));

        root.setText("root");
        root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootActionPerformed(evt);
            }
        });
        jPanel2.add(root, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 60, 60));

        fact.setText("fact");
        fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factActionPerformed(evt);
            }
        });
        jPanel2.add(fact, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 60, 60));

        power.setText("power");
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });
        jPanel2.add(power, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 60, 60));

        equal.setText("equal");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        jPanel2.add(equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 60, 60));

        restart.setText("restart");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });
        jPanel2.add(restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 60, 60));

        home.setText("jButton1");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel2.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 90, 50));

        next.setText("RANDOM");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 80, 50));

        N1.setText("1");
        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });
        jPanel2.add(N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 100, 140));

        N2.setText("2");
        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });
        jPanel2.add(N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, 140));

        N3.setText("3");
        N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N3ActionPerformed(evt);
            }
        });
        jPanel2.add(N3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 100, 140));

        N4.setText("4");
        N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N4ActionPerformed(evt);
            }
        });
        jPanel2.add(N4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 100, 140));

        jLayeredPane2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setPreferredSize(new java.awt.Dimension(670, 520));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.setVisible(false);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wine SK\\Desktop\\java\\photo\\2play1.png")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wine SK\\Desktop\\java\\photo\\another\\universe_dribbble.gif")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(720, 720));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 672, 520));

        play1.setText("back");
        play1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play1ActionPerformed(evt);
            }
        });
        jPanel3.add(play1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 441, 98, 68));

        jLayeredPane2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        jPanel1.disable();                    //press play button to play game //show play game page
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        randomNum();                          //when come to play game program will be rundom number
    }//GEN-LAST:event_playActionPerformed

    private void how2playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_how2playActionPerformed
        jPanel1.disable();                    //press how2play button to how to play page
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_how2playActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);                       //press exit button to exit programe
    }//GEN-LAST:event_exitActionPerformed

    private void play1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play1ActionPerformed
        jPanel1.disable();                    //press back home button to first page
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_play1ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        randomNum();                         //rundom new number
    }//GEN-LAST:event_nextActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        jPanel1.disable();                   //press home button to first page
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootActionPerformed
                                             //calculate root
            int root = (int) Math.sqrt(Integer.parseInt(ans.getText().trim()));
            STRans = String.valueOf(root);
            ans.setText(STRans);
    }//GEN-LAST:event_rootActionPerformed

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
                                             //press number rundomed move box bottom
        if(b1){             //เช็คว่าถูกกดไปรึยัง ถ้ายังก็กดได้
            if(readyop){    ///เช็คว่าก่อนกดเลขได้กดเครื่องหมายอะไรมั้ย ถ้ากดก็จะคำนวณให้
                ans.setText(String.valueOf(cal(n1,Integer.parseInt(ans.getText().trim()))));
                number1.setIcon(null);
                b1=false;
                readyop=false;
            }
            else{           ///ถ้ายังไม่กด เลขจะหายไป แล้วกล่องด้านจะโชว์เลขนั้น
                String num = String.valueOf(n1);
                ans.setText(num);        ////เขียนเลขลงในกล่อง
                num = String.valueOf(n2);           ////ยังคงแสดงเลข n2,n3,n4 ไว้อยู่
                number2.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                num = String.valueOf(n3);
                number3.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                num = String.valueOf(n4);
                number4.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                number1.setIcon(null);              ////ทำให้ n1 หายไป
                b1=false;                           /////ถูกกดไปแล้ว
                b2=b3=b4=true;                      /////ยังไม่ถูกกด
            }
        }
    }//GEN-LAST:event_N1ActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
        if(b2){
            if(readyop){
                ans.setText(String.valueOf(cal(n2,Integer.parseInt(ans.getText().trim()))));
                number2.setIcon(null);
                b2=false;
                readyop=false;
            }
            else{
                String num = String.valueOf(n2);
                ans.setText(num);
                num = String.valueOf(n1);
                number1.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                num = String.valueOf(n3);
                number3.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                num = String.valueOf(n4);
                number4.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                number2.setIcon(null);
                b2=false;
                b1=b3=b4=true;
            }
        }
    }//GEN-LAST:event_N2ActionPerformed

    private void N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N3ActionPerformed
        if(b3){
            if(readyop){
                ans.setText(String.valueOf(cal(n3,Integer.parseInt(ans.getText().trim()))));
                number3.setIcon(null);
                b3=false;
                readyop=false;
            }
            else{
                String num = String.valueOf(n3);
                ans.setText(num);
                num = String.valueOf(n1);
                number1.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                num = String.valueOf(n2);
                number2.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                num = String.valueOf(n4);
                number4.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                number3.setIcon(null);
                b3=false;
                b1=b2=b4=true;
            }
        }
    }//GEN-LAST:event_N3ActionPerformed

    private void N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N4ActionPerformed
        if(b4){
            if(readyop){
                ans.setText(String.valueOf(cal(n4,Integer.parseInt(ans.getText().trim()))));
                number4.setIcon(null);
                b4=false;
                readyop=false;
            }
            else{
                String num = String.valueOf(n4);
                ans.setText(num);
                num = String.valueOf(n1);
                number1.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                num = String.valueOf(n2);
                number2.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                num = String.valueOf(n3);
                number3.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
                number4.setIcon(null);
                b4=false;
                b2=b3=b1=true;
            }
        }
    }//GEN-LAST:event_N4ActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
                                                //press restart button แล้วเลขกลับมาเป็นแบบตอนแรก
        STRans = "";
        op = "";
        ans.setText(STRans);            ///เซตให้กล่องข้างล่างว่าง
        String num = String.valueOf(n1);  ///ทำให้ n1,n2,n3,n4 แสดงเลขเหมือนเดิมแบบตอนแรก
        number1.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
        num = String.valueOf(n2);
        number2.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
        num = String.valueOf(n3);
        number3.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
        num = String.valueOf(n4);
        number4.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
        b1=b2=b3=b4=true;                ///เซตให้ทุกค่ายังไม่ถูกกด
        readyop=false;                   ///เซตว่ายังไม่มีการกดเครื่องหมายอะไร
    }//GEN-LAST:event_restartActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
                                             //calculate plus
        readyop=true;
        op="+";
    }//GEN-LAST:event_plusActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
                                             //calculate minus
        readyop=true;
        op="-";
    }//GEN-LAST:event_minusActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
                                             //calculate multi
        readyop=true;
        op="*";
    }//GEN-LAST:event_multiActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
                                             //calculate divide
        readyop=true;
        op="/";
    }//GEN-LAST:event_divideActionPerformed

    private void factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factActionPerformed
                                             //calculate factorial
            int number = Integer.parseInt(ans.getText().trim());
            int fact = 1;
            for(int i=1;i<=number;i++){    
                fact=fact*i;
            }
            STRans = String.valueOf(fact);
            ans.setText(STRans);  
    }//GEN-LAST:event_factActionPerformed

    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerActionPerformed
                                             //calculate power
        readyop=true;
        op="^";
    }//GEN-LAST:event_powerActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
                                             //show number calculated
        if(checksum() && checknum()){        ///โดยเช็คว่าค่าเท่ากับ 24 มั้ย และ เช็คว่าใช้ทุกตัวมั้ย
            score += 1;
            randomNum();
        }
        scoreText.setText(String.valueOf(score));     
    }//GEN-LAST:event_equalActionPerformed
       
    private void randomNum(){
                                        //random number
        Random r = new Random();
        n1 = r.nextInt(10);
        String num = String.valueOf(n1);
        number1.setIcon(new javax.swing.ImageIcon(setIconNum(num))); ///เลือกรูปใน method setIconNum
        n2 = r.nextInt(10);
        num = String.valueOf(n2);
        number2.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
        n3 = r.nextInt(10);
        num = String.valueOf(n3);
        number3.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
        n4 = r.nextInt(10);
        num = String.valueOf(n4);
        number4.setIcon(new javax.swing.ImageIcon(setIconNum(num)));
        STRans="";
        op="";
        ans.setText(STRans);
        b1=b2=b3=b4=true;
    }
    
    private String setIconNum(String num){
                                         //รันดอมเลขมาแล้ว ก็มาเลือกรูปภาพ
        switch(num){
            case "0":
                return "C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\0.png";
            case "1":
                return "C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\1.png";
            case "2":
                return "C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\2.png";
            case "3":
                return "C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\3.png";
            case "4":
                return "C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\4.png";
            case "5":
                return "C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\5.png";
            case "6":
                return "C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\6.png";
            case "7":
                return "C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\7.png";
            case "8":
                return "C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\8.png";
            case "9":
                return "C:\\Users\\Wine SK\\Desktop\\java\\photo\\number\\9.png";
        }
        return "";
        
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JButton N1;
    private javax.swing.JButton N2;
    private javax.swing.JButton N3;
    private javax.swing.JButton N4;
    private javax.swing.JLabel ans;
    private javax.swing.JLabel bg;
    private javax.swing.JButton divide;
    private javax.swing.JButton equal;
    private javax.swing.JButton exit;
    private javax.swing.JButton fact;
    private javax.swing.JButton home;
    private javax.swing.JButton how2play;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton minus;
    private javax.swing.JButton multi;
    private javax.swing.JButton next;
    private javax.swing.JLabel number1;
    private javax.swing.JLabel number2;
    private javax.swing.JLabel number3;
    private javax.swing.JLabel number4;
    private javax.swing.JButton play;
    private javax.swing.JButton play1;
    private javax.swing.JButton plus;
    private javax.swing.JButton power;
    private javax.swing.JButton restart;
    private javax.swing.JButton root;
    private javax.swing.JLabel scoreText;
    private javax.swing.JLabel scorelabel;
    // End of variables declaration//GEN-END:variables

    private int cal(int number,int number2) {
        switch(op){
            case("+"):
                op = "";
                return number2 + number ;
            case("-"):
                op = "";
                return number2 - number ;     
            case("*"):
                op = "";
                return number2 * number ;    
            case("/"):
                op = "";
                return number2 / number ;  
            case("^"):
                op = "";
                return (int)Math.pow(number2, number);
        }
        return 0;
    }
    
    private boolean checksum(){ 
                                 //check คำนวณแล้วได้เท่ากับ 24 มั้ย
        if(ans.getText().equals("24"))
            return true;
        return false;
    }
    private boolean checknum(){
                                 //เช็คว่าใช้เลขครบทุกตัวมั้ย
        if(b1==false && b2==false && b3==false && b4==false){
            return true;
        }
        return false;
    }
}
